### PR TITLE
Add some guidance for a continuous deploy setup using semantic release

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Added initial project setup guide, multiple guides can be added here. Later we can add a readme summarising each.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
@timker thoughts on this?

**Comment by timker** [comment]
while i like the idea of Semantic Release, a couple of talking points:

> Don’t let your friends dump git logs into changelogs.
https://keepachangelog.com/en/1.0.0/

Thoughts?

Is the versioning for feat,fix just the commit message? or can it support branch names as well.
Can we enforce a commit message structure? If we consolidate, we probably want to consider with our private repo's as well.

GreenKeeper is a pretty good solution for public js repo's, we need to consider private and other languages as well, if the goal is to standardise (e.g dotnet, docker etc etc)

Sydney Team is more likely to use AzurePipelines rather than travis, it's exactly the same, but more integrated with our private workflows (though the release pipelines are in preview, and still a little rough around the edges). I'm not sure we you be able to limit ourselves to one build step (yarn verify) And may need additional (e.g. "Publish Code Coverage Results" etc) some of the steps can't be executed via script.

While it's not probably a common use case for our public repo's, will semantic-release with work with lerna?

where do the release notes get generated? Does the npm release directly link back to the github release?
We have got a bit of value with out NuGet packages directly linking to the changelog so it's easy to make any decisions around the upgrade.

**Comment by JakeGinnivan** [comment]
We have given a strategy similar to https://keepachangelog.com/en/1.0.0/ a solid go, it causes a heap of pain on a repo with any sort of commit traffic, it constantly conflicts.

It just works on commits, commits which do not conform to the changelog format get ignored. It also allows you to commit `docs:` or `chore:` which when merged to not trigger a release to NPM. You can use something like https://github.com/commitizen/cz-cli to make it easy to conform to the commit message format. Semantic release runs on every merge to master, if there are commits which should be released it will release as a major, minor or patch depending on the commit messages, tag, create the github release (with release notes generated from the commit messages) and push to NPM. It's pretty great, I wish our internal builds were this simple. It's one of the reasons I am moving our libraries to OSS because an OSS toolchain is easier to maintain.

Also, we use teamcity for builds and Jira for our changelogs internally. My goals for this was a much simpler and free workflow for open source projects. For the moment my goal is to make it super easy for someone to release a small NPM library as open source. If it wasn't an internal project it's annoying to setup builds/releases etc, this makes end to end setup about 30 minutes.

The idea around yarn verify is a sensible default, if you need more complex builds then you can just expand the `.travis.yml` to do what you need.

As for supporting mono repos, https://github.com/semantic-release/semantic-release/issues/193 is a discussion on the subject. TLDR, not properly. Though this blog post goes through it https://michaljanaszek.com/blog/lerna-conventional-commits

Currently it doesn't link back to the release notes in the github release, is probably something there is a plugin to do though

Good talking points!

**Comment by timker** [comment]
since this is a guide, and not a requirement, happy to move forward

**Review by timker — APPROVED** [review]

**Pull request merged**
